// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsHXAc5lVPPEkAQQSp1EImhtU5BmBAcAI',
    appId: '1:979588453803:web:00eccad35fa29f7950aeee',
    messagingSenderId: '979588453803',
    projectId: 'myapp-8b2ba',
    authDomain: 'myapp-8b2ba.firebaseapp.com',
    storageBucket: 'myapp-8b2ba.appspot.com',
    measurementId: 'G-8WSCVQ32KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpptRQn9jrw8QSAGDFgiQM-2-OZNlIa_o',
    appId: '1:979588453803:android:f8c5df493634f74d50aeee',
    messagingSenderId: '979588453803',
    projectId: 'myapp-8b2ba',
    storageBucket: 'myapp-8b2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHkyeIEyFzXAeJWcHflwPHhb_N_NqtNuw',
    appId: '1:979588453803:ios:fb0b9e693cec6b2750aeee',
    messagingSenderId: '979588453803',
    projectId: 'myapp-8b2ba',
    storageBucket: 'myapp-8b2ba.appspot.com',
    iosClientId: '979588453803-f0nvu0sjp5q0nh3nvslbredl738at4ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHkyeIEyFzXAeJWcHflwPHhb_N_NqtNuw',
    appId: '1:979588453803:ios:fb0b9e693cec6b2750aeee',
    messagingSenderId: '979588453803',
    projectId: 'myapp-8b2ba',
    storageBucket: 'myapp-8b2ba.appspot.com',
    iosClientId: '979588453803-f0nvu0sjp5q0nh3nvslbredl738at4ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample1',
  );
}
